apiVersion: v1
kind: Secret
metadata:
  name: somaz-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:somaz94/helm-chart-template.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    xxxx # Change to the private key registered in github
    xxxx
    ... 
    -----END OPENSSH PRIVATE KEY-----


